version: 2
updates:
  - package-ecosystem: "pub"
    directory: "/government_simulator"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
